sudo: required

services:
  - docker
  
before_install:
  - whoami
  - pwd
  - docker build --tag base base
  - docker build --tag openmpi openmpi
  - docker build --tag mpich mpich
  - docker build --tag mpich-blcr mpich-blcr

script:
  - bin/test.sh
